export const TYPES = {
  USER: {
    LOGIN: '[USER] LOGIN',
    LOGOUT: '[USER] LOGOUT',
    CHANGE_NAME: '[USER] CHANGE NAME',
  },
  SETTINGS: {
    SET_SETTINGS: '[SETTTINGS] SET_SETTINGS',
  },
};
