export const TYPES = {
  USER: {
    LOGIN: '[USER] LOGIN',
    LOGOUT: '[USER] LOGOUT',
    CHANGE_NAME: '[USER] CHANGE NAME',
  },
  SETTINGS: {
    SET_SETTINGS: '[SETTTINGS] SET_SETTINGS',
  },
  NOTIFICATIONS: {
    SHOW_SNACKBAR: 'notificationsReducer/showSnackbar',
    HIDE_SNACKBAR: '[NOTIFICATIONS] HIDE_SNACKBAR',
  },
  TRENDS: {
    APPEND_MEDIAS: '[TRENDS] APPEND_MEDIAS',
    CLEAR_MEDIAS: '[TRENDS] CLEAR_MEDIAS',
    SET_CURRENT_TREND: '[TRENDS] SET_CURRENT_TREND',
  },
};
